name: testapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.3.0
  flutter_otp_text_field: ^1.1.1
  get: ^4.6.5

  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_database: ^10.2.2

  syncfusion_flutter_charts: ^21.2.8

  #icon package

  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.7.1
  provider: ^6.0.5



  sleek_circular_slider: ^2.0.1
  rainbow_color: ^2.0.1
  animated_background: ^2.0.0
  animations: ^2.0.3
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/logo.jpg
  image_dark: assets/images/logo.jpg
  resize: 0.3

  android_12:
    image: assets/images/logo.jpg
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.jpg
    icon_background_color_dark: "#121212"
    resize: 0.5

    web: false
flutter:
  assets:
    - assets/images/logo.jpg
    - assets/images/aaa.png
    - assets/images/nani.jpg
    - lib/src/utils/theme/widget_themes/
    - assets/images/GoogleLogo.png
    - lib/src/features/authentication/screens/Login/widgets/
    - assets/svg/


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
